<a href="https://colab.research.google.com/github/saurabh-parkar/Music-Genre-Classification/blob/master/Image_Processing%2C_Class_encodings%2C_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pylab
from matplotlib import cm
import numpy as np
import os
import librosa
import matplotlib.pyplot as plt
import librosa.display
import cv2
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
import pickle


Using TensorFlow backend.


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:

basepath = "/content/drive/My Drive/genres1000/genres/"
paths = []
for entry in os.listdir(basepath):
  if entry == "meta":
    continue
  
  dir1 = os.path.join(basepath, entry) +'/'
  print(dir1)
  for filename in os.listdir(dir1):
   audio_path = filename

   x , sr = librosa.load(dir1 + audio_path)
   mel = librosa.feature.melspectrogram(y=x, sr=sr)
   log_power = librosa.power_to_db(mel, ref=np.max)
   pylab.figure(figsize=(5,5))
   pylab.axis('off') 
   pylab.axes([0., 0., 1., 1.], frameon=False, xticks=[], yticks=[])
   
   ax = librosa.display.specshow(log_power, cmap=cm.jet)
   fig = ax.get_figure()
   
   str1 = filename[0:-4];
   fig.savefig('/content/drive/My Drive/genres1000/mel_Images/'+ str1+'.png')
   plt.close(fig)



In [0]:
import pandas as pd

In [0]:
with open("/content/drive/My Drive/genres1000/genres/meta/bextract_single.mf") as file: # Use file to refer to the file object

   data = file.readlines()

In [0]:
file_to_genre = {}
for i in data[:-2]:
  music_file = i.split('\t')
  file_to_genre[music_file[0].split('/')[-1][:-3]] = music_file[1][:-1]



In [0]:
len(file_to_genre)

1094

In [0]:
import pandas as pd

In [0]:
df = pd.DataFrame.from_dict(file_to_genre,orient='index')

In [0]:
df

0
classical.00000  classical
classical.00001  classical
classical.00002  classical
classical.00003  classical
classical.00004  classical
...                    ...
metal.00096          metal
metal.00097          metal
metal.00098          metal
metal.00099          metal
metal.00100          metal

[1094 rows x 1 columns]

In [0]:
genres = list(df[0].unique())

In [0]:
genres

['classical',
 'country',
 'disco',
 'hiphop',
 'jazz',
 'pop',
 'rock',
 'reggae',
 'blues',
 'metal']

In [0]:
labels =  {genres[i]:i for i in range(len(genres))}

In [0]:
labels

{'blues': 8,
 'classical': 0,
 'country': 1,
 'disco': 2,
 'hiphop': 3,
 'jazz': 4,
 'metal': 9,
 'pop': 5,
 'reggae': 7,
 'rock': 6}

In [0]:
inv_labels = {i:genres[i] for i in range(len(genres))}

In [0]:
inv_labels

{0: 'classical',
 1: 'country',
 2: 'disco',
 3: 'hiphop',
 4: 'jazz',
 5: 'pop',
 6: 'rock',
 7: 'reggae',
 8: 'blues',
 9: 'metal'}

In [0]:
targets = []
for m,n in file_to_genre.items():
  encoding = np.zeros(len(labels), dtype = 'uint8')
  encoding[labels[n]] = 1
  targets.append(encoding)

In [0]:
targets

[array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=u

In [0]:
df['targets'] = targets

In [0]:
df.head()

0                         targets
classical.00000  classical  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
classical.00001  classical  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
classical.00002  classical  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
classical.00003  classical  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
classical.00004  classical  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [0]:
df1 = df.drop(columns=0)

In [0]:
df1 = df1.reset_index()

In [0]:
df1

index                         targets
0     classical.00000  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
1     classical.00001  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2     classical.00002  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
3     classical.00003  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
4     classical.00004  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
...               ...                             ...
1089      metal.00096  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
1090      metal.00097  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
1091      metal.00098  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
1092      metal.00099  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
1093      metal.00100  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

[1094 rows x 2 columns]

In [0]:
dict1 = {}
for i,j in zip(df1['index'], df1['targets']):
  dict1[i] = j

In [0]:
dict1

{'classical.00000': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00001': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00002': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00003': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00004': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00005': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00006': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00007': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00008': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00009': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00010': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00011': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00012': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 'classical.00013': array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=

In [0]:
dict1['classical.00000']

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [0]:
image1 = []
target1 = []
data = []
i = 0
path = '/content/drive/My Drive/genres1000/mel_Images/'
for img in os.listdir(path):
  print(i)
  i+=1
  #photo = load_img(path + img, target_size=(128,128))
  photo1 = cv2.imread(path + img,0)
  #photo = img_to_array(photo, dtype='uint8')
  photo2 = cv2.resize(photo1,(64,64))
  #tag = file_to_genre[img[:-4]]
  data.append([photo2,dict1[img[:-4]]])
  #image1.append(photo)
  #target1.append(dict1[img[:-4]])


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [0]:
len(data)

1000

In [0]:
import random

random.shuffle(data)

In [0]:
X = []
Y = []

for f, l in data:
  X.append(f)
  Y.append(l)

In [0]:
len(X)

1000

In [0]:
#(-1,128,128,3) for 3d inputs
X = np.array(X).reshape(-1,64,64)

In [0]:
import pickle

pickle_out = open('/content/drive/My Drive/genres1000/X_1d.pickle','wb')
pickle.dump(X,pickle_out)
pickle_out.close()

In [0]:
pickle_out = open('/content/drive/My Drive/genres1000/Y_1d.pickle','wb')
pickle.dump(Y,pickle_out)
pickle_out.close()

In [0]:
pickle_in = open("/content/drive/My Drive/genres1000/X_1d.pickle","rb")
X = pickle.load(pickle_in)

In [0]:
X.shape

(1000, 64, 64)

In [0]:
X[51]

array([[[128,   0,   0],
        [128,   0,   0],
        [128,   0,   0],
        ...,
        [128,   0,   0],
        [128,   0,   0],
        [128,   0,   0]],

       [[128,   0,   0],
        [128,   0,   0],
        [128,   0,   0],
        ...,
        [128,   0,   0],
        [128,   0,   0],
        [128,   0,   0]],

       [[128,   0,   0],
        [128,   0,   0],
        [133,   0,   0],
        ...,
        [128,   0,   0],
        [128,   0,   0],
        [128,   0,   0]],

       ...,

       [[  0, 224, 254],
        [  0,  25, 255],
        [  0,  55, 246],
        ...,
        [  0,  62, 255],
        [  0,  75, 241],
        [  0,  69, 255]],

       [[ 33, 255, 214],
        [  0,  96, 255],
        [  0, 134, 255],
        ...,
        [  0,  60, 255],
        [  0, 168, 255],
        [  0, 180, 255]],

       [[153, 255,  94],
        [101, 255, 146],
        [111, 255, 136],
        ...,
        [125, 255, 122],
        [ 61, 255, 185],
        [ 20, 249, 226]]

In [0]:
import numpy as np

In [0]:
import tensorflow as tf
import pickle
from keras.models import Sequential
from keras.layers import Conv2D, Dense, Dropout, Activation, Flatten, Conv2D,MaxPooling2D,MaxPooling2D, AveragePooling2D, Conv1D, MaxPooling1D, TimeDistributed,LSTM, BatchNormalization, Conv3D
from keras.optimizers import Adam


Using TensorFlow backend.


In [0]:
pickle_in = open("/content/drive/My Drive/genres1000/X_1d.pickle","rb")
X = pickle.load(pickle_in)

In [0]:
pickle_in = open("/content/drive/My Drive/genres1000/Y_1d.pickle","rb")
Y = pickle.load(pickle_in)

In [0]:
X_norm = tf.keras.utils.normalize(X,axis =1)

In [0]:
X_norm = np.array(X_norm)
Y = np.array(Y)

In [0]:
from sklearn.model_selection import train_test_split

trainX, testX, trainY, testY = train_test_split(X_norm, Y, test_size=0.2, random_state=1)

In [0]:
trainX = np.array(trainX)
trainY = np.array(trainY)

In [0]:
trainX.shape

(800, 64, 64)

In [0]:
trainY.shape[1]

10

In [0]:
n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainY.shape[1]

In [0]:
n_timesteps

64

In [0]:
n_features

64

In [0]:
trainX1 = np.expand_dims(trainX, axis=2)

In [0]:
trainX1.shape

(800, 128, 1, 128)

In [0]:
trainX_ = []
for i in trainX:
  m = i.flatten()
  trainX_.append(m)

In [0]:
len(trainX_[0])

4096

In [0]:
trainX_ = np.expand_dims(trainX_, axis=2)

In [0]:
trainX_.shape

(800, 4096, 1)

In [0]:
# 1D convolution

model = Sequential()
model.add(Conv1D(128,3,input_shape = (4096,1)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Conv1D(128,3))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Conv1D(128,3))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Flatten())


model.add(LSTM(128, dropout=0.05, recurrent_dropout=0.35, return_sequences=True, input_shape=(1,523520)))
model.add(LSTM(32,  dropout=0.05, recurrent_dropout=0.35, return_sequences=False))

model.add(Dense(10, activation='softmax'))


model.add(TimeDistribued(Dense(10, activation='softmax')))

opt = Adam(lr=0.001,decay=0.00001)

model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics=['accuracy'])


ValueError: ignored

In [0]:

'''
modelx.add(Conv2D(filters=128, kernel_size=3, activation='relu', kernel_initializer='he_uniform', padding='same', input_shape=(n_timesteps,n_features,3)))
modelx.add(MaxPooling1D(2))
modelx.add(Dropout(0.5))

model.add(Conv2D(filters=128, kernel_size=3, activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(MaxPooling1D((2)))
model.add(Dropout(0.5))

model.add(Conv2D(filters=64, kernel_size=3, activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(MaxPooling1D((2)))
model.add(Dropout(0.2))
'''


model = Sequential()
model.add(TimeDistributed(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same', input_shape=(128, 128, 3))))
model.add(TimeDistributed(MaxPooling2D((2, 2))))
model.add(TimeDistributed(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same')))
model.add(TimeDistributed(MaxPooling2D((2, 2))))
model.add(TimeDistributed(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same')))
model.add(TimeDistributed(MaxPooling2D((2, 2))))
model.add(TimeDistributed(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same')))
model.add(TimeDistributed(MaxPooling2D((2, 2))))

model.add(LSTM(256, return_sequences=True))
model.add(TimeDistributed(Dense(8)))
model.add(Activation('softmax'))


model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [0]:
model = Sequential()

model.add(
    TimeDistributed(
        Conv3D(64, (3, 3,3), activation='relu'), 
        input_shape=(800, 128,128, 1)
    )
)
model.add(TimeDistributed(MaxPooling3D((2, 2,2),padding='same',strides=(1, 1))))

model.add(TimeDistributed(Conv3D(128, (4,4,4), activation='relu')))
model.add(TimeDistributed(MaxPooling3D((2, 2,2), padding='same',strides=(1, 1))))

model.add(TimeDistributed(Conv3D(256, (4,4,4), activation='relu')))
model.add(TimeDistributed(MaxPooling3D((2, 2,2), padding='same',strides=(1, 1))))

# extract features and dropout 
model.add(TimeDistributed(Flatten()))

# input to LSTM
model.add(LSTM(256, return_sequences=False, dropout=0.5))

# classifier with sigmoid activation for multilabel
model.add(Dense(10, activation='sigmoid'))

model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics=['accuracy'])

ValueError: ignored

In [0]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_14 (Conv1D)           (None, 4094, 128)         512       
_________________________________________________________________
batch_normalization_14 (Batc (None, 4094, 128)         512       
_________________________________________________________________
activation_14 (Activation)   (None, 4094, 128)         0         
_________________________________________________________________
dropout_14 (Dropout)         (None, 4094, 128)         0         
_________________________________________________________________
conv1d_15 (Conv1D)           (None, 4092, 128)         49280     
_________________________________________________________________
batch_normalization_15 (Batc (None, 4092, 128)         512       
_________________________________________________________________
activation_15 (Activation)   (None, 4092, 128)        

In [0]:
model.fit(trainX_,trainY, validation_split=0.1, epochs = 7)

Train on 720 samples, validate on 80 samples
Epoch 1/7
720/720 [==============================] - 6s 9ms/step - loss: 14.5958 - acc: 0.0944 - val_loss: 14.3048 - val_acc: 0.1125
Epoch 2/7
720/720 [==============================] - 6s 8ms/step - loss: 14.5958 - acc: 0.0944 - val_loss: 14.3048 - val_acc: 0.1125
Epoch 3/7
720/720 [==============================] - 6s 8ms/step - loss: 14.5958 - acc: 0.0944 - val_loss: 14.3048 - val_acc: 0.1125
Epoch 4/7
720/720 [==============================] - 6s 8ms/step - loss: 14.5958 - acc: 0.0944 - val_loss: 14.3048 - val_acc: 0.1125
Epoch 5/7
512/720 [====================>.........] - ETA: 1s - loss: 14.5755 - acc: 0.0957

KeyboardInterrupt: ignored

In [0]:
trainX[1].shape

(128, 128, 3)

In [0]:
trainX[1].reshape(-1)

array([0.20323106, 0.03232373, 0.        , ..., 0.04053855, 0.09355968,
       0.11584664])

In [0]:
trainX[1][1].reshape(-1)

array([0.20323106, 0.03422512, 0.        , 0.12068308, 0.00669296,
       0.        , 0.14503831, 0.01277313, 0.        , 0.12455074,
       0.06280528, 0.        , 0.1382034 , 0.06630377, 0.        ,
       0.19074738, 0.02850434, 0.        , 0.12989558, 0.07507222,
       0.00724424, 0.15956809, 0.04373579, 0.        , 0.15514508,
       0.04721237, 0.        , 0.14767505, 0.06272871, 0.        ,
       0.16510171, 0.017359  , 0.        , 0.10199374, 0.03347118,
       0.        , 0.14053574, 0.00881933, 0.        , 0.11716908,
       0.0398135 , 0.        , 0.14024867, 0.03502321, 0.        ,
       0.17559976, 0.03451842, 0.        , 0.15211984, 0.02474329,
       0.        , 0.15318971, 0.03704096, 0.        , 0.15440504,
       0.02479218, 0.        , 0.1705525 , 0.04570906, 0.        ,
       0.15660868, 0.03171706, 0.        , 0.13872821, 0.03587385,
       0.        , 0.13065181, 0.03407389, 0.        , 0.1269914 ,
       0.02670845, 0.        , 0.13141757, 0.0261995 , 0.     

In [0]:
from keras.optimizers import Adam

In [0]:
model = Sequential()

model.add(Conv2D(128, (3, 3), kernel_initializer='he_uniform', padding='same', input_shape=(128, 128, 3)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(128, (3, 3), kernel_initializer='he_uniform', padding='same', input_shape=(128, 128, 3)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(64, (3, 3), kernel_initializer='he_uniform', padding='same', input_shape=(128, 128, 3)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(32, (3, 3), kernel_initializer='he_uniform', padding='same', input_shape=(128, 128, 3)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Flatten())
model.add(Dense(128, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(64, activation='relu', kernel_initializer='he_uniform'))


model.add(Dense(10, activation='softmax'))

opt = Adam(lr=0.001,decay=0.001)

model.compile(loss='categorical_crossentropy', optimizer = opt, metrics=['accuracy'])

In [0]:
model.fit(trainX,trainY, validation_split=0.1, epochs = 10)

Train on 720 samples, validate on 80 samples
Epoch 1/10
720/720 [==============================] - 9s 12ms/step - loss: 2.1787 - acc: 0.2764 - val_loss: 1.9998 - val_acc: 0.2250
Epoch 2/10
720/720 [==============================] - 3s 5ms/step - loss: 1.5442 - acc: 0.4417 - val_loss: 1.5568 - val_acc: 0.4125
Epoch 3/10
720/720 [==============================] - 3s 5ms/step - loss: 1.2318 - acc: 0.5653 - val_loss: 1.4277 - val_acc: 0.4125
Epoch 4/10
720/720 [==============================] - 3s 5ms/step - loss: 1.0996 - acc: 0.6000 - val_loss: 1.3174 - val_acc: 0.5125
Epoch 5/10
720/720 [==============================] - 3s 5ms/step - loss: 0.8661 - acc: 0.7056 - val_loss: 1.0789 - val_acc: 0.5875
Epoch 6/10
720/720 [==============================] - 3s 5ms/step - loss: 0.6713 - acc: 0.7792 - val_loss: 1.4432 - val_acc: 0.5000
Epoch 7/10
720/720 [==============================] - 3s 5ms/step - loss: 0.5887 - acc: 0.7875 - val_loss: 1.0396 - val_acc: 0.6375
Epoch 8/10
720/720 [==========

In [0]:
model.evaluate(testX, testY)

200/200 [==============================] - 0s 2ms/step


[1.032574064731598, 0.62]

In [0]:
predictions = model.predict([testX])

In [0]:
model.evaluate(x=testX, y=testY)

200/200 [==============================] - 0s 1ms/step


[0.2964641761779785, 0.8944999885559082]

In [0]:
print(np.argmax(predictions[0]))

8


In [0]:
pred = []
for i in range(len(predictions)):
  pred.append(np.argmax(predictions[i]))

In [0]:
pred

[8,
 6,
 7,
 7,
 8,
 7,
 1,
 0,
 0,
 1,
 5,
 8,
 8,
 8,
 8,
 0,
 4,
 7,
 5,
 0,
 6,
 0,
 8,
 9,
 6,
 5,
 4,
 6,
 4,
 8,
 0,
 8,
 6,
 1,
 0,
 6,
 4,
 1,
 1,
 4,
 7,
 8,
 7,
 8,
 1,
 8,
 8,
 6,
 4,
 4,
 6,
 4,
 8,
 4,
 1,
 0,
 4,
 4,
 4,
 5,
 6,
 4,
 4,
 6,
 1,
 4,
 1,
 4,
 5,
 4,
 8,
 9,
 0,
 1,
 0,
 6,
 4,
 6,
 7,
 4,
 0,
 4,
 1,
 4,
 0,
 4,
 0,
 4,
 1,
 7,
 4,
 8,
 1,
 4,
 5,
 4,
 9,
 7,
 1,
 5,
 4,
 0,
 4,
 4,
 1,
 0,
 0,
 4,
 4,
 4,
 0,
 2,
 8,
 6,
 0,
 9,
 4,
 4,
 8,
 4,
 1,
 4,
 4,
 5,
 1,
 6,
 9,
 6,
 4,
 1,
 4,
 5,
 0,
 7,
 8,
 6,
 8,
 8,
 8,
 7,
 0,
 5,
 4,
 0,
 4,
 6,
 0,
 6,
 8,
 4,
 4,
 4,
 4,
 4,
 8,
 0,
 8,
 7,
 1,
 1,
 7,
 4,
 7,
 4,
 6,
 1,
 8,
 4,
 7,
 1,
 0,
 6,
 4,
 4,
 0,
 4,
 8,
 6,
 0,
 8,
 7,
 6,
 4,
 0,
 4,
 1,
 4,
 8,
 6,
 8,
 4,
 4,
 1,
 0,
 8,
 7,
 9,
 8,
 4,
 9]

In [0]:
true = []
for i in testY:
  true.append(list(i))

In [0]:
trueY = []
for i in true:
  trueY.append(i.index(1))

In [0]:
trueY


[8,
 9,
 3,
 7,
 6,
 3,
 2,
 5,
 5,
 4,
 5,
 9,
 9,
 6,
 8,
 5,
 5,
 3,
 5,
 0,
 6,
 0,
 8,
 9,
 9,
 7,
 4,
 9,
 1,
 8,
 8,
 8,
 9,
 2,
 0,
 9,
 1,
 2,
 6,
 4,
 3,
 7,
 3,
 3,
 1,
 8,
 3,
 6,
 7,
 4,
 6,
 7,
 7,
 6,
 6,
 0,
 2,
 1,
 4,
 5,
 9,
 7,
 3,
 2,
 2,
 0,
 1,
 2,
 3,
 6,
 6,
 9,
 4,
 1,
 0,
 2,
 8,
 2,
 3,
 2,
 0,
 8,
 1,
 4,
 1,
 3,
 0,
 0,
 1,
 3,
 7,
 9,
 2,
 7,
 5,
 1,
 9,
 5,
 3,
 5,
 2,
 0,
 1,
 1,
 7,
 0,
 0,
 7,
 4,
 2,
 8,
 6,
 2,
 9,
 0,
 9,
 6,
 4,
 7,
 1,
 6,
 4,
 1,
 5,
 5,
 9,
 9,
 9,
 0,
 2,
 1,
 5,
 0,
 3,
 8,
 2,
 8,
 7,
 9,
 5,
 0,
 5,
 6,
 2,
 1,
 6,
 0,
 2,
 2,
 1,
 5,
 1,
 4,
 4,
 8,
 0,
 8,
 6,
 1,
 2,
 3,
 4,
 3,
 4,
 2,
 6,
 7,
 1,
 3,
 7,
 0,
 9,
 5,
 3,
 0,
 5,
 8,
 9,
 6,
 4,
 7,
 9,
 7,
 2,
 5,
 2,
 1,
 9,
 9,
 8,
 1,
 4,
 2,
 0,
 8,
 2,
 9,
 8,
 2,
 9]

In [0]:
for i,j in zip(trueY, pred):
  print(i,j)

8 8
9 6
3 7
7 7
6 8
3 7
2 1
5 0
5 0
4 1
5 5
9 8
9 8
6 8
8 8
5 0
5 4
3 7
5 5
0 0
6 6
0 0
8 8
9 9
9 6
7 5
4 4
9 6
1 4
8 8
8 0
8 8
9 6
2 1
0 0
9 6
1 4
2 1
6 1
4 4
3 7
7 8
3 7
3 8
1 1
8 8
3 8
6 6
7 4
4 4
6 6
7 4
7 8
6 4
6 1
0 0
2 4
1 4
4 4
5 5
9 6
7 4
3 4
2 6
2 1
0 4
1 1
2 4
3 5
6 4
6 8
9 9
4 0
1 1
0 0
2 6
8 4
2 6
3 7
2 4
0 0
8 4
1 1
4 4
1 0
3 4
0 0
0 4
1 1
3 7
7 4
9 8
2 1
7 4
5 5
1 4
9 9
5 7
3 1
5 5
2 4
0 0
1 4
1 4
7 1
0 0
0 0
7 4
4 4
2 4
8 0
6 2
2 8
9 6
0 0
9 9
6 4
4 4
7 8
1 4
6 1
4 4
1 4
5 5
5 1
9 6
9 9
9 6
0 4
2 1
1 4
5 5
0 0
3 7
8 8
2 6
8 8
7 8
9 8
5 7
0 0
5 5
6 4
2 0
1 4
6 6
0 0
2 6
2 8
1 4
5 4
1 4
4 4
4 4
8 8
0 0
8 8
6 7
1 1
2 1
3 7
4 4
3 7
4 4
2 6
6 1
7 8
1 4
3 7
7 1
0 0
9 6
5 4
3 4
0 0
5 4
8 8
9 6
6 0
4 8
7 7
9 6
7 4
2 0
5 4
2 1
1 4
9 8
9 6
8 8
1 4
4 4
2 1
0 0
8 8
2 7
9 9
8 8
2 4
9 9


In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(trueY, pred)

0.635

In [0]:
testY

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=uint8)

In [0]:
model.fit(X_norm,Y,batch_size=32, validation_split=0.1, epochs = 10)

Train on 900 samples, validate on 100 samples
Epoch 1/10
896/900 [============================>.] - ETA: 0s - loss: 0.1500 - acc: 0.9414

KeyboardInterrupt: ignored

In [0]:
model = Sequential()

model = Sequential()
model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same', input_shape=(128, 128, 3)))
model.add(AveragePooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(AveragePooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(AveragePooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(AveragePooling2D((2, 2)))

model.add(Flatten())
model.add(Dense(128, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(64, activation='relu', kernel_initializer='he_uniform'))

model.add(Dense(10, activation='softmax'))

model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [0]:
model.fit(X_norm,Y,batch_size=32, validation_split=0.1, epochs = 10)

Train on 900 samples, validate on 100 samples
Epoch 1/10
900/900 [==============================] - 97s 108ms/step - loss: 0.3206 - acc: 0.9000 - val_loss: 0.3017 - val_acc: 0.9000
Epoch 2/10
900/900 [==============================] - 97s 107ms/step - loss: 0.2880 - acc: 0.9038 - val_loss: 0.2749 - val_acc: 0.9010
Epoch 3/10
900/900 [==============================] - 96s 107ms/step - loss: 0.2632 - acc: 0.9056 - val_loss: 0.2521 - val_acc: 0.9070
Epoch 4/10
900/900 [==============================] - 96s 107ms/step - loss: 0.2425 - acc: 0.9109 - val_loss: 0.2328 - val_acc: 0.9120
Epoch 5/10
900/900 [==============================] - 97s 107ms/step - loss: 0.2293 - acc: 0.9139 - val_loss: 0.2331 - val_acc: 0.9110
Epoch 6/10
900/900 [==============================] - 97s 107ms/step - loss: 0.2189 - acc: 0.9167 - val_loss: 0.2195 - val_acc: 0.9070
Epoch 7/10
900/900 [==============================] - 97s 107ms/step - loss: 0.2138 - acc: 0.9193 - val_loss: 0.2351 - val_acc: 0.9120
Epoch 8/1

In [0]:
model = Sequential()

model = Sequential()
model.add(Conv2D(128, (3, 3), activation='relu', padding='same', input_shape=(128, 128, 3)))
model.add(AveragePooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
model.add(AveragePooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(AveragePooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(AveragePooling2D((2, 2)))

model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))

model.add(Dense(10, activation='softmax'))

model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [0]:
model.fit(X_norm,Y,batch_size=32, validation_split=0.1, epochs = 10)

Train on 900 samples, validate on 100 samples
Epoch 1/10
900/900 [==============================] - 98s 109ms/step - loss: 0.3206 - acc: 0.9000 - val_loss: 0.3302 - val_acc: 0.9000
Epoch 2/10
900/900 [==============================] - 96s 107ms/step - loss: 0.3015 - acc: 0.8998 - val_loss: 0.2794 - val_acc: 0.9020
Epoch 3/10
900/900 [==============================] - 96s 107ms/step - loss: 0.2755 - acc: 0.9028 - val_loss: 0.2678 - val_acc: 0.9020
Epoch 4/10
900/900 [==============================] - 97s 107ms/step - loss: 0.2649 - acc: 0.9061 - val_loss: 0.2565 - val_acc: 0.9080
Epoch 5/10
832/900 [==========================>...] - ETA: 7s - loss: 0.2592 - acc: 0.9062 

KeyboardInterrupt: ignored